DEVOPS-75 [CICD] Workflow de publication d'une release d'un package NPM
Sonergia/concerto-home-front-core pull request #55
Opened 2022-10-18 07:45 UTC by pcomble

2022-10-18 09:07 UTC, jledoux-sonergia commented
@pcomble Ca me semble très bien correspondre au besoin. Est ce que tu as pu tester la création d'une release ?

Je me dis qu'on pourrait rendre ce workflow plus générique et paramètrable pour l'ajouter ultérieurement au repo github reusable workflow, mais pour le moment c'est superflu puisque c'est le seul package npm qu'on voudrait garder privé.

Par contre, il nous faudrait un process Confluence qui décrit la création d'un package (j'ai vu que ça passait par une release github) et son intégration dans une application node.js, qu'on pourra ensuite fournir à @Mathieu-Tribouillard qui l'utilisera au quotidien et discuter de cette approche avec lui pour voir ce que ces changements impliquent.

2022-10-18 09:09 UTC, jledoux-sonergia commented
Edit: plutôt dans le README du core à ce stade que dans Confluence

2022-10-18 13:49 UTC, jledoux-sonergia requested changes

2022-10-18 13:49 UTC, jledoux-sonergia commented on .github/workflows/npm-publish-github-packages.yml
> +    types: [created]
Est ce qu'il ne faudrait pas plutôt mettre l'event release [published] ?
`types: [published]`
Car avec `created` je crois que ça veut dire que si on créé une release brouillon (ou draft) ça va quand même déclencher la CI

2022-10-18 13:49 UTC, jledoux-sonergia commented on .github/workflows/npm-publish-github-packages.yml
> +name: Node.js Package
Je rajouterai bien dans le titre "Publish Node.js package"

2022-10-18 13:49 UTC, jledoux-sonergia commented on package.json
> +  "name": "@sonergia/concerto-home-app-core",
Est ce que le fait de changer le nom du package va impacter mathieu dans ses déploiements que l'on rende ce repo privé ou qu'on le laisse public ?
C'est à dire que pour merger cette PR il va devoir changer la syntaxe dans les projets customer et partner ?

Aujourd'hui il utilise cette syntaxe dans le package.json:
`"concerto-home-app-core": "git+https://github.com/sonergia/concerto-home-front-core#1.1.0",`

Auquel cas il va falloir bien se synchroniser avec lui, car aujourd'hui la pratique pour tester unitaire les PRs et de faire pointer le package sur la branche de la PR.

2022-10-18 14:21 UTC, pcomble commented on package.json
> +  "name": "@sonergia/concerto-home-app-core",
Faudra passer avec la nouvelle syntaxe une fois le repo passé en privée.
Donc dans l'ordre : 
- utilisé le système de release et la création de tag qui vont bien.
- changer dans les autres repo l'appel
- passer ce repo en privée

Il n'y a aucun délai entre chaque étape, et ça devrait toujours fonctionner.

"git+https://github.com/sonergia/concerto-home-front-core#1.1.0" fait non pas appel à la release, mais au tag existant.

2022-10-18 14:30 UTC, jledoux-sonergia commented on package.json
> +  "name": "@sonergia/concerto-home-app-core",
Après en avoir discuté avec Mathieu on va utiliser le système de release et de publication de package quand on livrera en release et en production.

Pour livrer en test cependant, et pourvoir tester des PRs unitairement, le plus pratique pour le moment (au vue des très nombreuses modifications effectuées sur ce repo par le prestataire), est de laisser le repo public pour que Mathieu puisque continuer à faire pointer le package sur la branche de la PR dans ce cas précis.

Quant à la syntaxe côté customer et partner, si j'ai bien compris il faudra obligatoirement migrer vers:
`"@sonergia/concerto-home-app-core": "<release ou branch>"`

Il faut juste s'assurer que l'on peut toujours pointer vers une branche avec cette syntaxe tant que le repo reste public.

2022-10-18 14:32 UTC, pcomble commented on package.json
> +  "name": "@sonergia/concerto-home-app-core",
tant que le repo reste public on peux utiliser les deux syntaxes

2022-10-19 14:31 UTC, jledoux-sonergia commented
On va mettre ce point en stand by pour le moment, car cela pourrait alourdir le travail de @Mathieu-Tribouillard ce qui n'est pas le but recherché

2023-02-06 14:03 UTC, closed without merging